a = input('Digite algo:')
print('É da classe:', type(a))
print('É alfabético?', a.isalpha())
print('É numérico?', a.isnumeric())
print('É alfanumérico?', a.isalnum())
print('Tem somente espaços?', a.isspace())
print('Tem só minusculas?', a.islower())
print('Tem só maiusculas?', a.isupper())
print('Está capitalizada?', a.istitle())
